services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skincare-app
    restart: always
    environment:
      # Connect to external MySQL service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_server:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SECRET_KEY: ${SECRET_KEY:-changethissecretkey}
      ACCESS_TOKEN_EXPIRATION_MS: ${ACCESS_TOKEN_EXPIRATION_MS:-3600000}
      REFRESH_TOKEN_EXPIRATION_MS: ${REFRESH_TOKEN_EXPIRATION_MS:-86400000}
    ports:
      - "8080:8080"
    networks:
      - backend
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql_server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data_vol:/var/lib/mysql # Persistent storage
    networks:
      - backend

volumes:
  mysql_data_vol: # Persistent MySQL data volume

networks:
  backend:
    driver: bridge
